package game.icon;

public enum TileIcon {
	MINESWEEPER_0,
	MINESWEEPER_1,
	MINESWEEPER_2,
	MINESWEEPER_3,
	MINESWEEPER_4,
	MINESWEEPER_5,
	MINESWEEPER_6,
	MINESWEEPER_7,
	MINESWEEPER_8,
	MINESWEEPER_X,
	MINESWEEPER_M,
	MINESWEEPER_F,
	MINESWEEPER_C
}
